pipeline {
    agent any
    environment {
        DOCKER_HOST = "tcp://host.docker.internal:2375"
    }
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/Harsha03D/OneData-Assessment.git'
            }
        }
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                sh 'npm test'
            }
        }
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t jenkins-docker-app .'
            }
        }
        stage('Run Docker Container') {
            steps {
                sh 'docker run -d -p 8080:3000 jenkins-docker-app'
            }
        }
    }
}