pipeline {
    agent any

    stages {

        stage('Build') {
            steps {
                dir('CD_Jenkins_Docker') {
                    sh 'npm install'
                }
            }
        }

        stage('Test') {
            steps {
                dir('CD_Jenkins_Docker') {
                    sh 'npm test || echo "No tests found"'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('CD_Jenkins_Docker') {
                    sh 'docker build -t jenkins-docker-app .'
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                sh 'docker ps -q --filter "ancestor=jenkins-docker-app" | xargs -r docker stop'
                sh 'docker ps -a -q --filter "ancestor=jenkins-docker-app" | xargs -r docker rm'
                sh 'docker run -d -p 3000:3000 jenkins-docker-app'
            }
        }
    }
}
