pipeline {

    agent any

    stages {

        stage('Build') {
            steps {
                dir('CD_Jenkins_Docker') {
                    sh 'npm install'
                }
            }
        }

        stage('Test') {
            steps {
                dir('CD_Jenkins_Docker') {
                    sh 'npm test || echo "No tests found"'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('CD_Jenkins_Docker') {
                    sh 'docker build -t jenkins-docker-app .'
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                echo "Running Docker container..."
                sh '''
                # Stop and remove any container using port 3000
                docker ps --filter "publish=3000" -q | xargs -r docker stop
                docker ps -a --filter "publish=3000" -q | xargs -r docker rm
                
                # Remove old image if exists (optional clean-up)
                docker images -q jenkins-docker-app | xargs -r docker rmi -f
                
                # Run new container
                docker run -d -p 3000:3000 jenkins-docker-app
                '''
            }
        }
    }
}